name: "Milestone Sync"
description: "Moves issues and pull requests to the next milestone if it is released and tagged"
author: "jcfranco"
inputs:
  repo-token:
    description: "The GITHUB_TOKEN secret"
runs:
  using: "node12"
  main: "dist/index.js"
